sudo: required
dist: precise
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - gcc-5
      - g++-5
      - gcc-6
      - g++-6
      - cmake
      - cmake-data
      - libatlas-base-dev
      - libfftw3-dev
      - libgsl0-dev
      - libcfitsio3-dev

matrix:
  include:
    - os: linux
      compiler: gcc
      python: 3.6
      env:
        - CXX_COMPILER=g++-5
        - CC_COMPILER=gcc-5

    - os: linux
      compiler: gcc
      python: 3.6
      env:
        - CXX_COMPILER=g++-6
        - CC_COMPILER=gcc-6

script:
  - mkdir build
  - cd build
  - export CC=${CC_COMPILER} && export CXX=${CXX_COMPILER}
  - cmake .. && make